#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parse": "lda.ipynb",
         "getDF": "lda.ipynb",
         "freq_words": "lda.ipynb"}

modules = ["lda.py"]

git_url = "https://github.com/fastai/data-science-bowl-2019/tree/master/"

def custom_doc_links(name): return None